# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 568737b665d1009414e54c653f603033547c2b0188219e60f59f632f4aa50418735709d7b1790d397bdb9245a72fb04ce4f73add2cc2b634a7b7c7cede0246fe

test:
  secret_key_base: 67d72f7355f905e03801ce0b2bf2d361ad55531c4f1023b63ed8583b5f088a74f8d5e76a91ce8bedc7a85e35bea2fa7f531eea294ee246c10189a759c2ae8085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
